# Generated by Django 5.0.6 on 2024-07-04 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mechanics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('job_title', models.CharField(max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('stock_level', models.IntegerField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopapp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('vin', models.CharField(max_length=17)),
                ('license_plate', models.CharField(max_length=15)),
                ('date_in', models.DateTimeField(auto_now_add=True)),
                ('date_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('In Service', 'In Service'), ('Ready', 'Ready')], default='In Service', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_owner', to='shopapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateTimeField(auto_now_add=True)),
                ('service_type', models.CharField(max_length=200)),
                ('service_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], max_length=20)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid')], max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('customer_attended', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_service_record', to='shopapp.customer')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopapp.mechanics')),
                ('parts_used', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopapp.inventory')),
                ('car_fixed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_service_record', to='shopapp.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.mechanics')),
            ],
        ),
    ]
